from __future__ import annotations

import os
import html
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _text(value: Any) -> str:
    return html.escape(str(value)) if value not in (None, "") else "Unavailable"


def create_pdf(report: dict[str, Any], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    styles = getSampleStyleSheet()
    title = ParagraphStyle("NirikshaTitle", parent=styles["Title"], alignment=TA_CENTER, textColor=colors.HexColor("#164e63"), spaceAfter=8)
    heading = ParagraphStyle("NirikshaHeading", parent=styles["Heading2"], textColor=colors.HexColor("#164e63"), spaceBefore=10, spaceAfter=5)
    body = ParagraphStyle("NirikshaBody", parent=styles["BodyText"], fontSize=8.5, leading=11)
    small = ParagraphStyle("NirikshaSmall", parent=body, fontSize=7.5, leading=9)

    doc = SimpleDocTemplate(str(output_path), pagesize=A4, rightMargin=14 * mm, leftMargin=14 * mm, topMargin=14 * mm, bottomMargin=14 * mm)
    story: list[Any] = [
        Paragraph("NIRIKSHA", title),
        Paragraph("Legal Metrology Compliance Report", styles["Heading1"]),
        Spacer(1, 5),
    ]

    summary_rows = [
        [Paragraph("Report ID", body), Paragraph(_text(report["report_id"]), body), Paragraph("Scan ID", body), Paragraph(_text(report["scan_id"]), body)],
        [Paragraph("Product", body), Paragraph(_text(report.get("product_name")), body), Paragraph("Overall status", body), Paragraph(_text(report.get("overall_status")).upper(), body)],
        [Paragraph("Scan date/time", body), Paragraph(_text(report.get("scanned_at")), body), Paragraph("Generated", body), Paragraph(_text(report.get("generated_at")), body)],
        [Paragraph("Generated by", body), Paragraph(_text(report.get("officer_name")), body), Paragraph("Role", body), Paragraph("Officer", body)],
    ]
    story.append(Table(summary_rows, colWidths=[28 * mm, 63 * mm, 30 * mm, 55 * mm], style=TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0fdfa")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#f0fdfa")),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ])))

    extracted = report.get("extracted_data") or {}
    story.append(Paragraph("Extracted product information", heading))
    extracted_rows = [[Paragraph("Declaration", body), Paragraph("Value", body), Paragraph("Confidence", body)]]
    for name, item in extracted.get("fields", {}).items():
        if not isinstance(item, dict):
            continue
        confidence = item.get("confidence")
        confidence_text = f"{float(confidence) * 100:.0f}%" if confidence is not None else "Unavailable"
        extracted_rows.append([Paragraph(name.replace("_", " ").title(), small), Paragraph(_text(item.get("value")), small), Paragraph(confidence_text, small)])
    story.append(Table(extracted_rows, colWidths=[55 * mm, 100 * mm, 21 * mm], repeatRows=1, style=TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#164e63")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cbd5e1")), ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ])))

    story.append(Paragraph("Compliance summary", heading))
    summary = report.get("summary") or {}
    story.append(Paragraph(f"{summary.get('total_checks', 0)} checks: {summary.get('compliant', 0)} compliant, {summary.get('violations', 0)} violations, {summary.get('review', 0)} requiring review.", body))
    story.append(Paragraph("Individual compliance checks", heading))
    for index, check in enumerate(report.get("checks") or [], 1):
        story.append(Paragraph(f"{index}. {_text(check.get('name'))} — {_text(check.get('status')).upper()}", body))
        for label in ("value", "requirement", "explanation", "evidence", "confidence"):
            if label == "confidence":
                value = check.get(label)
                value = f"{float(value) * 100:.0f}%" if value is not None else "Unavailable"
            else:
                value = check.get(label)
            story.append(Paragraph(f"<b>{label.title()}:</b> {_text(value)}", small))
        story.append(Spacer(1, 4))

    doc.build(story)
