import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Eye, FileWarning, Loader2, Plus, RefreshCw } from 'lucide-react';
import { useApp } from '@/store';
import { EmptyState, PageHeader } from '@/components/ui';
import type { Complaint } from '@/types';

const labels: Record<string, string> = { new: 'New', viewed: 'Viewed', 'in-progress': 'In Progress', 'action-taken': 'Action Taken', resolved: 'Resolved', closed: 'Closed' };
const classes: Record<string, string> = { new: 'bg-brand-50 text-brand-700', viewed: 'bg-warning-50 text-warning-700', 'in-progress': 'bg-warning-50 text-warning-700', review: 'bg-warning-50 text-warning-700', investigating: 'bg-purple-50 text-purple-700', 'action-taken': 'bg-purple-50 text-purple-700', resolved: 'bg-success-50 text-success-700', closed: 'bg-ink-100 text-ink-700' };
function formatDate(value?: string) { return value ? new Date(value).toLocaleString() : '—'; }

export function Complaints() {
  const { role, user, complaints, complaintsLoading, refreshComplaints, addComplaint, scans, showToast } = useApp();
  const [selected, setSelected] = useState<Complaint | null>(null);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ product: '', category: 'Packaging declaration', description: '', location: user.location || '', scanId: '' });
  useEffect(() => {
    const timer = window.setTimeout(() => { void refreshComplaints({ search: search.trim(), status }); }, 250);
    return () => window.clearTimeout(timer);
  }, [refreshComplaints, search, status]);
  const visible = useMemo(() => complaints.filter((item) => (!search || [item.id, item.product, item.organizationName, item.description].join(' ').toLowerCase().includes(search.toLowerCase())) && (!status || item.status === status)), [complaints, search, status]);
  const submit = async () => { if (!form.product.trim() || !form.description.trim()) { showToast('error', 'Product and complaint description are required.'); return; } const ok = await addComplaint({ product: form.product.trim(), category: form.category, description: form.description.trim(), location: form.location.trim(), scanId: form.scanId || undefined }); if (ok) { setForm({ product: '', category: 'Packaging declaration', description: '', location: user.location || '', scanId: '' }); setShowForm(false); } };
  if (selected) return <ComplaintDetail complaint={selected} back={() => setSelected(null)} />;
  return <div>
    <PageHeader title="Complaints" subtitle={role === 'organization' ? 'Submit and track complaints raised by your organization.' : 'View complaints and current administrative status from the database.'} actions={<><button className="btn-secondary" onClick={() => void refreshComplaints()}><RefreshCw className="w-4 h-4" />Refresh</button>{role === 'organization' && <button className="btn-primary" onClick={() => setShowForm(!showForm)}><Plus className="w-4 h-4" />Submit complaint</button>}</>} />
    {showForm && <section className="card p-5 mb-5"><h2 className="font-semibold text-ink-900">Submit a complaint</h2><div className="grid md:grid-cols-2 gap-3 mt-4"><input className="input" placeholder="Product name" value={form.product} onChange={(e) => setForm({ ...form, product: e.target.value })} /><input className="input" placeholder="Complaint category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /><input className="input" placeholder="Location" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /><select className="input" value={form.scanId} onChange={(e) => setForm({ ...form, scanId: e.target.value })}><option value="">Link a scan (optional)</option>{scans.map((scan) => <option key={scan.id} value={scan.id}>{scan.product} · {scan.id}</option>)}</select><textarea className="input md:col-span-2 min-h-28" placeholder="Describe the complaint" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="flex justify-end gap-2 mt-4"><button className="btn-secondary" onClick={() => setShowForm(false)}>Cancel</button><button className="btn-primary" onClick={() => void submit()}>Submit to database</button></div></section>}
    <section className="card p-4 mb-5"><div className="grid md:grid-cols-[1fr_220px] gap-3"><input className="input" placeholder="Search complaint ID, product, or description" value={search} onChange={(e) => setSearch(e.target.value)} /><select className="input" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div></section>
    {complaintsLoading ? <div className="card p-10 text-center text-ink-500"><Loader2 className="w-5 h-5 animate-spin mx-auto mb-2" />Loading complaints from the database…</div> : visible.length === 0 ? <EmptyState icon={<FileWarning className="w-5 h-5" />} title="No complaints found" description="No complaint records match the current filters." /> : <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead className="bg-ink-50"><tr>{['Complaint', 'Product / Organization', 'Location', 'Category', 'Submitted', 'Status', 'Action'].map((h) => <th className="table-th" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-ink-100">{visible.map((item) => <tr key={item.id}><td className="table-td font-medium">{item.id}</td><td className="table-td"><div>{item.product}</div><div className="text-xs text-ink-500 mt-1">{item.organizationName || item.submittedBy || '—'}</div></td><td className="table-td">{item.location}</td><td className="table-td">{item.category}</td><td className="table-td text-xs text-ink-500">{formatDate(item.date)}</td><td className="table-td"><span className={`badge ${classes[item.status] || 'bg-ink-100 text-ink-700'}`}>{labels[item.status] || item.status}</span></td><td className="table-td"><button className="btn-secondary px-3 py-1.5 text-xs" onClick={() => setSelected(item)}><Eye className="w-3.5 h-3.5" />View</button></td></tr>)}</tbody></table></div></div>}
  </div>;
}

function ComplaintDetail({ complaint, back }: { complaint: Complaint; back: () => void }) {
  const { loadComplaint, showToast } = useApp();
  const [detail, setDetail] = useState(complaint);
  useEffect(() => { void loadComplaint(complaint.id).then(setDetail).catch((error) => showToast('error', error instanceof Error ? error.message : 'Complaint details could not be loaded.')); }, [complaint.id, loadComplaint, showToast]);
  return <div><PageHeader title={detail.id} subtitle="Complaint detail from the NIRIKSHA database." actions={<button className="btn-secondary" onClick={back}><ArrowLeft className="w-4 h-4" />Back to complaints</button>} /><div className="grid lg:grid-cols-[1.3fr_.7fr] gap-5"><section className="card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-ink-900">{detail.product}</h2><p className="text-sm text-ink-500 mt-1">{detail.organizationName || detail.submittedBy || 'Organization'}</p></div><span className={`badge ${classes[detail.status] || 'bg-ink-100 text-ink-700'}`}>{labels[detail.status] || detail.status}</span></div><dl className="grid sm:grid-cols-2 gap-4 mt-6 text-sm"><div><dt className="text-ink-500">Category</dt><dd className="font-medium mt-1">{detail.category}</dd></div><div><dt className="text-ink-500">Location</dt><dd className="font-medium mt-1">{detail.location}</dd></div><div><dt className="text-ink-500">Submitted</dt><dd className="font-medium mt-1">{formatDate(detail.date)}</dd></div><div><dt className="text-ink-500">Last updated</dt><dd className="font-medium mt-1">{formatDate(detail.updatedAt)}</dd></div></dl><div className="mt-6"><h3 className="font-semibold">Description</h3><p className="mt-2 text-sm text-ink-600 whitespace-pre-wrap">{detail.description || 'No description provided.'}</p></div>{detail.evidenceImages?.length ? <div className="mt-6"><h3 className="font-semibold">Evidence</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3">{detail.evidenceImages.map((image, index) => <img key={`${image}-${index}`} src={image} alt={`Complaint evidence ${index + 1}`} className="aspect-square w-full rounded-lg object-cover border border-ink-200" />)}</div></div> : null}</section><aside className="space-y-5"><section className="card p-5"><h3 className="font-semibold">Related records</h3>{detail.relatedScan ? <p className="text-sm mt-3">Scan: <b>{detail.relatedScan.id}</b><br />Score: {detail.relatedScan.complianceScore ?? '—'} / 100<br />Result: {detail.relatedScan.status}</p> : <p className="text-sm text-ink-500 mt-3">No related scan linked.</p>}{detail.relatedReport && <p className="text-sm mt-3">Report: <b>{detail.relatedReport.id}</b></p>}{detail.adminRemark && <p className="text-sm mt-4 border-t border-ink-100 pt-3"><b>Administrative remark:</b><br />{detail.adminRemark}</p>}</section><section className="card p-5"><h3 className="font-semibold">Status history</h3>{detail.history?.length ? <div className="mt-3 space-y-3">{detail.history.map((event) => <div className="border-l-2 border-brand-300 pl-3 text-sm" key={event.id}><b>{labels[event.newStatus.toLowerCase().replace('_', '-')] || event.newStatus}</b><div className="text-ink-500">{formatDate(event.changedAt)} · {event.changedBy || 'System'}</div></div>)}</div> : <p className="text-sm text-ink-500 mt-3">No status history recorded.</p>}</section></aside></div></div>;
}
